import { FILL_PATTERNS } from "@lilo/engine/light";

// Swatch PNGs are generated by `pnpm --filter @lilo/engine swatches` from the real stitch engine.
const swatches = import.meta.glob("../assets/fill-swatches/*.png", { eager: true, import: "default" }) as Record<string, string>;

export function swatchUrl(id: string): string | undefined {
  return swatches[`../assets/fill-swatches/${id}.png`];
}

/** The fill pattern grid: a preview of each pattern on a 40 x 30 mm shape, its name underneath. */
export function PatternPicker({ value, onPick }: { value: string; onPick: (id: string) => void }) {
  return (
    <div className="pattern-grid" role="listbox" aria-label="Fill pattern">
      {FILL_PATTERNS.map((p) => (
        <button key={p.id} role="option" aria-selected={value === p.id} className={`pattern${value === p.id ? " active" : ""}`} title={`${p.label}: ${p.help}`} onClick={() => onPick(p.id)} data-pattern={p.id}>
          <img src={swatchUrl(p.id)} alt="" loading="lazy" draggable={false} />
          <span>{p.label}</span>
        </button>
      ))}
    </div>
  );
}
