// Run with: pnpm test:scripts
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import { applyReadme, build, liloExtensions, renderDocs } from "./build-compat-docs.mjs";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const read = (p) => readFileSync(`${ROOT}${p}`, "utf8");
const inputs = () => ({
  machines: JSON.parse(read("data/compat/machines.json")),
  formats: JSON.parse(read("data/compat/formats.json")),
  threads: JSON.parse(read("data/threads/index.json")),
  hoops: JSON.parse(read("engine/src/hoops/library.json")),
  liloExts: liloExtensions(read("engine/src/formats/types.ts")),
});

test("reads the engine's format list", () => {
  assert.deepEqual(liloExtensions('export const FORMAT_EXTENSIONS = ["pes", "dst"] as const;'), ["dst", "pes"]);
  assert.throws(() => liloExtensions("nothing here"));
});

test("output is deterministic", () => {
  const a = renderDocs(inputs());
  const b = renderDocs(inputs());
  assert.equal(a.md, b.md);
  assert.equal(a.compatJson, b.compatJson);
  assert.equal(a.readmeBlock, b.readmeBlock);
});

test("counts come from the data", () => {
  const { counts } = build(inputs());
  assert.equal(counts.threadLines, 75);
  assert.equal(counts.hoops, 52);
  assert.ok(counts.threadColours > 20000);
  assert.ok(counts.machines >= 50);
});

test("no machine claims Wi-Fi was tested yet", () => {
  assert.equal(build(inputs()).counts.wifiTested, 0);
});

test("a wrong support level is rejected", () => {
  const i = inputs();
  i.machines.brands[0].models[0].liloSupport = "file";
  i.machines.brands[0].models[0].liloWifi = "untested";
  assert.throws(() => build(i), /liloSupport/);
});

test("formats.json out of step with the engine is rejected", () => {
  const i = inputs();
  i.liloExts = [...i.liloExts, "zzz"];
  assert.throws(() => build(i), /formats\.json/);
});

test("README block is replaced in place and inserted once", () => {
  const block = "<!-- compat:start (generated by scripts/build-compat-docs.mjs, do not edit by hand) -->\nX\n<!-- compat:end -->";
  const first = applyReadme("# T\n\nintro\n\n## Develop\n\nrun\n", block);
  assert.match(first, /X\n<!-- compat:end -->\n\n## Develop/);
  const second = applyReadme(first, block.replace("X", "Y"));
  assert.equal(second.split("compat:start").length, 2);
  assert.match(second, /Y/);
  assert.doesNotMatch(second, /X/);
});
